import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";

const isProtectedRoute = createRouteMatcher([
  "/dashboard(.*)",
  "/items(.*)",
  "/tasks(.*)",
  "/calendar(.*)",
  "/history(.*)",
]);

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const supabaseWs = supabaseUrl.replace(/^http/, "ws");

export default clerkMiddleware(
  async (auth, req) => {
    if (isProtectedRoute(req)) await auth.protect();
  },
  {
    signInUrl: "/sign-in",
    signUpUrl: "/sign-up",
    // Strict, per-request nonce CSP generated by Clerk (includes Clerk's own
    // origins); we only add Supabase for Realtime + REST.
    contentSecurityPolicy: {
      strict: true,
      directives: {
        "connect-src": supabaseUrl ? [supabaseUrl, supabaseWs] : [],
        "img-src": ["https://img.clerk.com"],
        "frame-ancestors": ["none"],
        "form-action": ["self"],
        "base-uri": ["self"],
        "object-src": ["none"],
        ...(process.env.VERCEL ? { "upgrade-insecure-requests": [] } : {}),
      },
    },
  },
);

export const config = {
  matcher: [
    // Skip Next.js internals and static files, unless found in search params
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    // Always run for API routes
    "/(api|trpc)(.*)",
  ],
};
